name: Update, Upgrade, and Clean System

on:
  schedule:
  - cron: '0 */6 * * *'

jobs:
  update-upgrade-clean:
    runs-on: self-hosted  
    
    steps:
    - name: Update the system packages
      run: |
        sudo apt-get update
        sudo echo "System packages have been updated."

    - name: Clean up packages cache
      run: |
        sudo apt-get clean
        sudo apt-get autoclean
        sudo echo "Package cache has been cleaned."

    - name: Verify update and clean
      run: |
        sudo echo "System packages have been updated and cache has been cleaned."
