name: Update, Upgrade, and Clean System

on:
  schedule:
    - cron: '*/5 * * * *'  # Mulai setiap 5 menit

jobs:
  update-upgrade-clean:
    runs-on: self-hosted  
    
    steps:
    - name: Update and Upgrade System Packages
      run: |
        sudo apt update -y && sudo apt upgrade -y
        sudo echo "System packages have been updated."

    - name: Clean up package cache
      run: |
        sudo apt clean  # Menghapus cache paket untuk membebaskan ruang
        echo "Package cache has been cleaned."

    - name: Verify update and clean
      run: |
        echo "System packages have been updated and cache has been cleaned."
